"""Common Parameters"""

import os.path

WINDOW_WIDTH : int = 1280
WINDOW_HEIGHT : int = 800

FILES_LOCATION = os.path.expanduser("~/.snekframe")
DATABASE_NAME = "photos.db"
PHOTOS_LOCATION = "files"

MAX_PATH_SIZE = 4096
MAX_FILENAME_SIZE = 256

TITLE_BAR_HEIGHT = 75

NUM_ROWS_PER_GALLERY_PAGE = 3
NUM_ITEMS_PER_GALLERY_ROW = 3
NUM_ITEMS_PER_GALLERY_PAGE = NUM_ROWS_PER_GALLERY_PAGE * NUM_ITEMS_PER_GALLERY_ROW

GIT_URL = "https://github.com"
ORGANISATION = "matthewar"
REPO_NAME = "snekframe"
REPO_URL = "/".join((GIT_URL, ORGANISATION, REPO_NAME))

VIRTUALENV_NAME = "env"
